# Generated by Django 3.2.25 on 2025-01-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='staffrecords',
        #     name='staff_salary',
        #     field=models.FloatField(default=0.0),
        # ),
    ]
