# Generated by Django 3.2.25 on 2025-02-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_staffrecords_staff_salary'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Staffs',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
    ]
